before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: cd spec/dummy ; rake db:test:load ; rake travis
gemfile:
  - Gemfile
language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
env:
  - "RAILS_VERSION=3.2"
  - "RAILS_VERSION=3.1"
  - "RAILS_VERSION=3.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - rvm: ruby-head
    - env: "RAILS_VERSION=master"
  exclude:
    - rvm: 2.0.0
      env: "RAILS_VERSION=3.0"
    - rvm: 2.0.0
      env: "RAILS_VERSION=3.1"
    - rvm: 1.9.2
      env: "RAILS_VERSION=master"
    - rvm: ruby-head
      env: "RAILS_VERSION=3.0"
    - rvm: ruby-head
      env: "RAILS_VERSION=3.1"
